

trigger:
- master
# strategy:
#  matrix:
#    linux:
#      operatingSystem: 'ubuntu-latest'
#    mac:
#      operatingSystem: 'macos-latest'
pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: Buildjob
      steps:
      - bash: echo "do the build"
- stage: DevDeploy
  jobs:
    - deployment: Devjob2
      strategy:
       runOnce:
         deploy:
          steps:
            - script: echo deploy to dev


