trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
- stage: devdep
  variables:
    environment: dev
  dependsOn: Build
  jobs:
  - job: devdep
    steps:
    - bash: echo Build $(environment)dep
- stage: qadep
  dependsOn: Build
  jobs:
  - job: qadep
    steps:
    - bash: echo Build qadep
- stage: proddep
  dependsOn: 
  - devdep
  - qadep
  jobs:
  - job: proddep
    steps:
    - bash: echo Build proddep

